services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./public:/var/www/public
      - ./lang:/var/www/lang
      - ./database/migrations:/var/www/database/migrations
      - db_data:/var/www/database
      - storage_data:/var/www/storage/app
      - ${VIDEOS_PATH}:/var/www/storage/app/videos
    env_file:
      - .env
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      CINEMACITY_COOKIE_USER_ID: ${CINEMACITY_COOKIE_USER_ID}
      CINEMACITY_COOKIE_PASSWORD: ${CINEMACITY_COOKIE_PASSWORD}
      CINEMACITY_EMAIL: ${CINEMACITY_EMAIL}
      CINEMACITY_PASSWORD: ${CINEMACITY_PASSWORD}
      FLARESOLVERR_URL: "http://flaresolverr:8191"
      TURNSTILE_SITE_KEY: ${TURNSTILE_SITE_KEY}
      TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY}
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info

volumes:
  db_data:
  storage_data:
  redis_data:
